### ISSUE TITLE
Alert für Tipeestream wird nicht gespeichert.

### ISSUE THREAD

**Issue by AmenitradieDruidin** [PhantomBotDE/PhantomBotDE#12]
Hiho, ich hatte den Fehler im Forum schon gemeldet aber ich glaube hier ist die Fehlermeldung besser aufgehoben oder ist es egal wo ich Fehler melde?
Also ich habe gerade im Discord einen Fehler gemeldet das der Alert für Tipeeestream sich nicht abspeichern lässt. In der Englischen Version ist aber wohl alles gut. 
Alle anderen Alarme sind gut. Habe auch Streamelements getestet und da hat er es abgespeichert. Also ich meine die Aktiveren oder nicht deaktiveren Option.
Nur Tipeeestream geht halt nicht. 
https://imgur.com/NngcziC
![Anmerkung 2019-f08-10 212853](https://user-images.githubusercontent.com/39033070/62826562-0c890f00-bbbe-11e9-9e07-7788869ae25e.jpg)

**Comment by Lapotor** [comment]
Problem wurde gefunden.
Wird mit anderen Fehlern mit einem Fix behoben.

**Comment by Lapotor** [comment]
Fix ist beim Testen.
Nightly Builds gibt es auf unserem Discord Server.
