### ISSUE TITLE
VIP Rolle kann bei Commands nicht ausgewählt werden

### ISSUE THREAD

**Issue by Se7enD** [PhantomBotDE/PhantomBotDE#14]
PhantomBot Version: 3.0.0-1 (Revision: 94c8a635)
O/S Version: Ubuntu
Web Browser Version (if Panel related): Chrome

Detailed Description:
Ich möchte bestimmte Commands und Audiohooks auf die VIP Rolle und aufwärts beschränken. Leider ist in der Liste lediglich die Rolle Hosters angegeben, die sich mir nicht erschließt. Ich habe gehört, dass im aktuellen nightly Build die VIP Rolle anwählbar sein soll. Dies würde ich mir auch für die deutsche Version wünschen.

**Comment by Lapotor** [comment]
Siehst du nur die `Hoster` Rolle oder lediglich keine `VIP` Rolle?

**Comment by Se7enD** [comment]
Ich sehe nur die Hosters Rolle. VIP taucht in der Liste gar nicht auf.

**Comment by Lapotor** [comment]
Ok ich habe in die Original Version einen Blick geworfen.
Dadurch das es in der PhantomBot v3.0.0 auch keine VIP Rolle zu Auswahl gibt bei Commands werden wir dies in dieser Version nicht ändern.

Nachweise:
- https://github.com/PhantomBot/PhantomBot/blob/fcc08b5182743d24f75f2e27bfc8f18c5333101f/resources/web/panel/js/pages/commands/custom.js#L123
- https://github.com/PhantomBot/PhantomBot/blob/fcc08b5182743d24f75f2e27bfc8f18c5333101f/resources/web/panel/js/pages/commands/custom.js#L220
- https://github.com/PhantomBot/PhantomBot/blob/fcc08b5182743d24f75f2e27bfc8f18c5333101f/resources/web/panel/js/pages/commands/default.js#L123

Sobald dies in der PhantomBot Original Version eingebaut ist werden wir dies natürlich übernehmen.

Sollten noch weiter fragen sein gerne hier.

**Comment by Se7enD** [comment]
Ok, danke für die Info.
Im nightly Build soll die Funktion bereits enthalten sein. Dann dürfte das ja bald zur Verfügung stehen.
