### ISSUE TITLE
Update Infos permanent da

### ISSUE THREAD

**Issue by Lapotor** [PhantomBotDE/PhantomBotDE#15]
PhantomBot Version: 3.0.0-1
O/S Version: Ubuntu 
Java Version: 1.8
Web Browser Version (if Panel related): Firefox

Detailed Description:
Seid der neusten Version wird der Update-Hinweis dauerhaft angezeigt.

**Comment by Sl0ter** [comment]
Selber Fehler bei mir

**Comment by DJDosKiller** [comment]
Habe das selbe problem.

**Comment by KayPure** [comment]
Jap, hier das gleiche. Hab schon gedacht ich bin zu dumm ein Update zu installieren ;)

**Comment by MaxJackson1** [comment]
Selbes Problem, ich hab auch kurz an mir gezweifelt haha

**Comment by Lapotor** [comment]
Sollte ebenfalls mit #18 behoben sein.
