### ISSUE TITLE
Docker Manifest nicht gefunden

### ISSUE THREAD

**Issue by ThePrimus** [PhantomBotDE/PhantomBotDE#22]
Hallo zusammen,

wenn ich versuche via Docker-Compose den Bot einzurichten erhalte ich folgenden Fehler:
ERROR: manifest for phantombotde/phantombotde:latest not found: manifest unknown: manifest unknown

**Comment by vesturo** [comment]
das docker image ist aktuell noch nicht verfügbar, der fehler sollte behoben sein sobald der Pull request durch ist und das Repo gebaut wurde.
