### ISSUE TITLE
Persistente Volumes

### ISSUE THREAD

**Issue by peterspat** [PhantomBotDE/PhantomBotDE#28]
PhantomBotDE Version: 3.1.2 (stable)
Operating System: Linux
Java Version: 11.0.4+10-LTS
Web Browser Version (if Panel related): n/a

Trotz Angabe eines peristenten Volumes, werden keine Daten gespeichert.

**Comment by Griefed** [comment]
Kann ich bestätigen. Wollte von einer regulären Installation des PhantomBots zur Docker-Version wechseln, aber alle Daten, welche ich von der Standard Installation in die Docker Volumes kopiert habe, werden ignoriert.
