### ISSUE TITLE
Keine Tags möglich

### ISSUE THREAD

**Issue by Daniel25996** [PhantomBotDE/PhantomBotDE#33]
PhantomBot Version: 3.3.0

Detailed Description:
Man kann keine Personen mehr taggen egal ob mit oder einer Variable, wie zum Beispiel (touser).
Dies gilt sowohl für Moderatoren als auch für den Admin beim Bot.

**Comment by Lapotor** [comment]
Wie genau meinst du das?
Kannst du bitte deine Schritte zu dem Problem beschreiben?

**Comment by Daniel250996** [comment]
Wenn ich im Chat eine Person taggen will, wie z.B. bei dem !game Command, geht der Tag zu der Person die den Command ausgelöst hat und nicht zu der, die getaggt werden sollte.
