### ISSUE TITLE
Regression: Docker Container v3.3

### ISSUE THREAD

**Issue by SvenC56** [PhantomBotDE/PhantomBotDE#34]
Detailed Description:

Hey, leider ist die neuste Version v3.3 nicht in Docker hub verfügbar. Ist dies in Zukunft geplant?

Vielen Dank.

**Comment by vesturo** [comment]
Hallo Sven, ich manage die Container und bin momentan mitten im Umzug, kann deshalb nicht sagen wann diese kommen. Ich gebe dir Bescheid wenn sie verfügbar wird!

**Comment by Lapotor** [comment]
Bin ebenso dabei does umzustellen.
https://github.com/PhantomBotDE/PhantomBotDE-Docker

**Comment by Lapotor** [comment]
Mit dieser Methode ist das bereitstellen vom Dockerimage nicht an ein extra process gekoppelt sonder läuft paralell durch verändern einer Variable.

**Comment by SvenC56** [comment]
Bei der Github Action könnte ich gerne helfen.

**Comment by SvenC56** [comment]
Ich habe mal einen ersten Wurf für die Docker Action geschrieben. Er zieht sich automatisch den neusten Tag und baut auf der Basis das Image und pushed es auf Dockerhub.

Siehe:
https://github.com/PhantomBotDE/PhantomBotDE-Docker/pull/1
