### ISSUE TITLE
Shoutout Übersetzungs änderung (Vorschlag)

### ISSUE THREAD

**Issue by Sl0ter** [PhantomBotDE/PhantomBotDE#36]
PhantomBot Version:3.3.0
O/S Version:Windows Server 2016
Java Version: 1.8.0_251

Detailed Description:
Die Anouncement bei "!shoutout" wird mit "Hey! Gib $1 einen Follow auf $2 - er spielte das letzte Mal $3!" herraus gegeben. 

Ist es möglich dies zu änder auf "Hey! Gib $1 einen Follow auf $2 - $1 spielte das letzte Mal $3!"

Danke schon mal im Vorraus. 
Wenn jemand eine Ahnung hat wo man dies selber ändern kann, dass es auch funktioniert, würde ich dies auch selber machen. 

Versucht habe ich es schon in der Datein "lang\german\handler\handlers-followHandler.js" jedoch ohne erfolg, auch das ändern eines wortes wurde nicht übernommen.

Mit freundlichen Grüßen
Sl0ter

**Comment by Saphiramina** [comment]
Ich kümmere mich darum :D! 

Danke o/

**Comment by Saphiramina** [comment]
Hab's mir eben nochmal angesehen und bemerkt warum das so da steht. Ich kann die Expression kein weiteres mal benutzen und werde mal intern Fragen diesbezüglich. Leider gibt es ja im Deutschen keine Nicht-Binäre Anrede.

**Comment by remplerus** [comment]
alternativ dazu: "Hey! Gib $1 einen Follow auf $2 - dort wurde zuletzt $3 gespielt!"
