### ISSUE TITLE
Ist das Ändern des Ports 25000 möglich?/ " Instanzen parallel laufen haben

### ISSUE THREAD

**Issue by globoxnoob** [PhantomBotDE/PhantomBotDE#37]
PhantomBot Version:
O/S Version:
Java Version:
Web Browser Version (if Panel related):

Detailed Description:

Guten Tag,

ich habe eine ziemlich allgemeine und wahrscheinlich doofe Frage.
Für einen kollegen und mich würde ich gerne den PhantomBot auf meinem Server laufen lassen.
Kann ich irgendwie die Porteinstellungen selbstständig ändern oder ist das nicht nötig/ möglich.
Ist es überhaupt möglich, zwei Instanzen laufen zu haben?

Gruß Globoxnoob

Steps to Reproduce:

Logs:

Screenshots (if applicable):

**Comment by remplerus** [comment]
es ist möglich mehrere instanzen parallel laufen zu lassen, wie das geht, weiß ich leider nicht. dementsprechend können auch die ports geändert werden.

**Comment by MentalFS** [comment]
Der Port kann in _botlogin.txt_ geändert werden.

Auf die Art kann man mehrere Instanzen laufen haben. Jeder Bot muss dabei aber auch seinen komplett eigenen Installationsordner haben.
