### ISSUE TITLE
Abenteuersystem ohne Funktion

### ISSUE THREAD

**Issue by LastSoldier80** [PhantomBotDE/PhantomBotDE#39]
PhantomBot Version: 3.3.0
O/S Version: any
Java Version: any
Web Browser Version (if Panel related): -/-

Detailed Description:
In der "games-adventureSystem.js" wird das Array "$.lang.register " u.a. mir der übersetzten Zeile "$.lang.register('adventuresystem.stories.default', 'wahr');" gefüllt. Da es sich hier um einen booleschen Wert handelt, ist das Nutzen des Abenteuersystems nicht möglich.
Bitte wieder auf "$.lang.register('adventuresystem.stories.default', 'true');" ändern.

**Comment by Thaliruth1** [comment]
Installiere dir das Englische Original. Phantombot 3.3.0 ist veraltet, und wird so scheinbar auch gar nicht mehr Supportet. Aktuell gibt es auf Englisch die Version 3.4.2 da es bei Twitch und co einige Änderungen gab, wird die Deutsche Version so oder so nicht mehr funktionieren. Daher die Englische Verwenden und alles selber lokalisieren, habe ich auch so gemacht, bis auf das Webinterface selbst.

**Comment by Fischfilet89** [comment]
Einfach die entsprechende Variable ins korrekte Format abändern, dann sollte das Modul wieder funktionieren
