### ISSUE TITLE
Unerwartete Ausgabe bei einem Shoutout zu einem User ohne Gameangabe

### ISSUE THREAD

**Issue by Brunsben** [PhantomBotDE/PhantomBotDE#40]
PhantomBot Version: 3.3.0
O/S Version:%
Java Version:%
Web Browser Version (if Panel related):%

Detailed Description:
Wenn ich die Übersetzung richtig lese sollte die Ausgabe bei einem Shoutout zu einem Streamer, der keine Kategorie angegeben hat eigentlich sein:
`Hey! Gib %%% einen Follow auf https://twitch.tv/%%%`

Ich bekomme aber folgende Ausgabe:
`Hey! Gib %%% einen Follow auf https://twitch.tv/%%% - er streamte das letzte Mal nicht sicher, ist Twitch auch nicht! `

Wo kommt da das  - `er streamte das letzte Mal nicht sicher, ist Twitch auch nicht!` her?

Steps to Reproduce:
Einen Shoutout zu einem Account machen, der kein Game angegeben hat ;)

**Comment by Thaliruth1** [comment]
Installiere dir das Englische Original. Phantombot 3.3.0 ist veraltet, und wird so scheinbar auch gar nicht mehr Supportet. Aktuell gibt es auf Englisch die Version 3.4.2 da es bei Twitch und co einige Änderungen gab, wird die Deutsche Version so oder so nicht mehr funktionieren. Daher die Englische Verwenden und alles selber lokalisieren, habe ich auch so gemacht, bis auf das Webinterface selbst.

**Comment by Brunsben** [comment]
Den Weg bin ich jetzt auch gegangen. Hab zwar wohl noch nicht alle Stellen erwischt, das meiste ist aber mittlerweile Deutsch.
