### ISSUE TITLE
Translation of PhantomBot v2.4.2.1

### ISSUE THREAD

**Issue by Lapotor** [PhantomBotDE/PhantomBotDE#8]
The latest version of PhantomBot was released with v2.4.2.1

**Comment by DjSni** [comment]
The latest version of PhantomBot was released with v3.0.0 !!!

**Comment by Lapotor** [comment]
@DjSni get done right next.

**Comment by vesturo** [comment]
@Lapotor is already working on, V3.0.0. Issue closed, thanks for informing US!

**Comment by vesturo** [comment]
Accidently closed it smh

**Comment by Lapotor** [comment]
Done.
